### ISSUE TITLE
Please tag 4.0.0

### ISSUE THREAD

**Issue by jakirkham** [conda/libconda#1]
It seems this is missing a tag for 4.0.0. On the other repo, this appears to be commit ( https://github.com/ilanschnell/libconda/commit/43c33dcb36de524e981b99c9c1f67ae4cf63954f ). Could we please have the same commit ( https://github.com/conda/libconda/commit/43c33dcb36de524e981b99c9c1f67ae4cf63954f ) tagged here, as well?

**Comment by ilanschnell** [comment]
Good catch!  I just tagged the same commit here.

**Comment by jakirkham** [comment]
Awesome. Thanks. Will close this out.
